#!/usr/bin/env bash
#Redirect the user to a new website.
apt-get -y update
apt-get -y install nginx
mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
new_string='server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://gist.github.com/carlessanagustin/9509d0d31414804da03b;\n\t}'
sed -i "s,server_name _;,$new_string," /etc/nginx/sites-available/defaultservice nginx restart
