#!/usr/bin/env bash
for file in *
do
    echo "Now sending $file"
    if [ "$file != $0" ]
    then
        scp -i "/home/usool/Usool-learn/alx_intranet_key" -o StrictHostKeyChecking=no "$file" "$1@$2":~
    fi
done
