#!/usr/bin/env bash
#Display "Y U no love me?!" on receiving SIGINT

exiting() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" >> /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love?!"' SIGINT
	trap 'echo "I hate the kill command" && exiting' SIGTERM
	trap 'exiting' SIGQUIT
done
