#!/usr/bin/env bash
# Conditionally prints "Best School"
ind=1
while [[ $ind -le 20 ]]
do
	echo "$ind"
	case $ind in
	"4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
	esac
	(( ind++ ))
done
